name: Run Jest

on:
  pull_request:
    branches:
    - 'main'
    - 'release-**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
          
      - name: Install packages
        run: yarn install
        
      - name: Run Jest
        run: yarn test:ci