name: Typecheck

on:
  pull_request:
    branches:
    - 'main'
    - 'release-**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      - name: Install packages
        run: npm install
        
      - name: Run tsc
        run: npm run typecheck